name: "[staging] Full Test Suite"
on:
  workflow_dispatch:

permissions:
    contents: write

jobs:
  all-tests:
    uses: IllarionarSem/GitHub-actions/.github/workflows/setup-java-test-env.yml@main
    with:
      gradle-task: test
      gradle-args: "-Denv=staging"

  publish-allure:
    needs: all-tests
    if: always()
    uses: IllarionarSem/GitHub-actions/.github/workflows/publish-allure-pages.yml@main
    with:
      allure-results-artifact: 'allure-results'
      report-folder: 'staging-full-test-suite'