name: "[staging] Full Test Suite"
on:
  workflow_dispatch:

permissions:
    contents: write
    actions: read

jobs:
  all-tests:
    uses: IllarionarSem/GitHub-actions/.github/workflows/run-gradle-test-and-publish-report.yml@main
    with:
      gradle-task: test
      gradle-args: "-Denv=staging"
      environment: staging
      report-folder: 'staging-full-test-suite'
