name: "Run Test By Tag"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag"
        required: true
        type: choice
        default: "smoke"
        options:
          - smoke
          - e2e

      env:
        description: "environment to run on"
        required: true
        type: choice
        default: "staging"
        options:
          - staging
          - develop
          - qa

jobs:
  test-by-tag:
    uses: IllarionarSem/GitHub-actions/.github/workflows/run-gradle-test-and-publish-report.yml@main
    with:
      report-folder: test-by-tag-${{ inputs.env }}-${{ inputs.tag }}
      environment: ${{ inputs.env }}
      gradle-task: test
      gradle-args: "-Dtag=${{ inputs.tag }} -Denv=${{ inputs.env }}"
