name: "Run Test By Tag"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag"
        required: true
        type: choice
        default: "smoke"
        options:
          - smoke
          - e2e

      env:
        description: "environment to run on"
        required: true
        type: choice
        default: "staging"
        options:
          - staging
          - develop
          - qa

jobs:
  all-tests:
    uses: IllarionarSem/GitHub-actions/.github/workflows/setup-java-test-env.yml@main
    with:
      gradle-task: test
      gradle-args: "-Dtag=${{ inputs.tag }} -Denv=${{ inputs.env }}"
