name: "Run Test By Tag"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag"
        required: true
        type: choice
        default: "smoke"
        options:
          - smoke
          - e2e

      env:
        description: "environment to run on"
        required: true
        type: choice
        default: "staging"
        options:
          - staging
          - develop
          - qa

jobs:
  all-tests:
    uses: IllarionarSem/GitHub-actions/.github/workflows/setup-java-test-env.yml@main
    with:
      gradle-task: test
      gradle-args: "-Dtag=${{ inputs.tag }} -Denv=${{ inputs.env }}"

  publish-allure:
    needs: all-tests
    if: always()
    uses: IllarionarSem/GitHub-actions/.github/workflows/publish-allure-pages.yml@main
    with:
      allure-results-artifact: 'allure-results'
      report-folder: 'test-by-tag-suite'
